---
title: "Reproducible Research - Introduction"
author: "Carlos Sanchez"
date: "2/8/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
install.packages("kernlab")
library(kernlab)
```




```{r}
data(spam)
set.seed(3435)
trainIndicator <- rbinom(nrow(spam), size = 1, prob = 0.5)
table(trainIndicator)
```


```{r}
trainSpam <- spam[trainIndicator == 1, ]
testSpam <- spam[trainIndicator == 0, ]

```



```{r}
names(trainSpam)
head(trainSpam)
```


```{r}
table(trainSpam$type)

```


```{r}
plot(log10(trainSpam$capitalAve + 1 ) ~ trainSpam$type)
```


```{r}
plot(log10(trainSpam[, 1:4] +1))
```




```{r}
hCluster <- hclust(dist(t(trainSpam[, 1:57])))
plot(hCluster)
```


```{r}
hClusterUpdated <- hclust(dist(t(log10(trainSpam[, 1:57] + 1))))
plot(hClusterUpdated)

```


```{r}
trainSpam$numType <- as.numeric(trainSpam$type) - 1
costFunction <- function(x, y) sum(x != (y > 0.5))
cvError <- rep(NA, 55)
library(boot)
for (i in 1:55) {
  lmFormula = reformulate(names(trainSpam)[i], response = "numType")
  glmFit = glm(lmFormula, family = "binomial", data = trainSpam)
  cvError[i] = cv.glm(trainSpam, glmFit, costFunction, 2)$delta[2]
}

##Which predictor has minimum cross-validated error?
names(trainSpam)[which.min(cvError)]
```




```{r}
#Use the best model from the group
predictionModel <- glm(numType ~ charDollar, family = "binomial", data = trainSpam)

#Get predictions on the test set
predictionTest <- predict(predictionModel, testSpam)
predictedSpam <- rep("nonspam", dim(testSpam)[1])

#Classify as 'spam' for those with prob > 0.5
predictedSpam[predictionModel$fitted > 0.5] = "spam"
```


```{r}
table(predictedSpam, testSpam$type)

```


```{r}
#Error rate
(61 + 458) / (1346 + 458 + 61 + 449)
```




```{r}


```




```{r}


```




```{r}


```




```{r}


```




```{r}


```




```{r}


```




```{r}


```




```{r}


```




```{r}


```

